### ISSUE TITLE
KeyError on loading model

### ISSUE THREAD

**Issue by SandeepBhutani** [marcogdepinto/Emotion-Classification-Ravdess#4]
What version of keras you used? I got following error:  
My python version is 3.6 and keras version is 2.0.6   

```
(/data/anaconda-envs/sand-dev) sandeep.bhutani@linux:/data/gitcodes/speechanalysis/Emotion-Classification-Ravdess$ python LivePredictions.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "LivePredictions.py", line 71, in <module>
    pred.load_model()
  File "LivePredictions.py", line 20, in load_model
    self.loaded_model = keras.models.load_model(self.path)
  File "/data/anaconda-envs/sand-dev/lib/python3.6/site-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/data/anaconda-envs/sand-dev/lib/python3.6/site-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/data/anaconda-envs/sand-dev/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/data/anaconda-envs/sand-dev/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/data/anaconda-envs/sand-dev/lib/python3.6/site-packages/keras/models.py", line 1204, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0
```

**Comment by SandeepBhutani** [comment]
I fixed it by setting up new conda environment using Python 3.7
